---
- hosts: laptop
  become: True
  gather_facts: True
  vars_files:
    - vars.yml
  roles:
    - { role: repositories, tags: repositories }
    - { role: packages, tags: packages }
    - { role: services, tags: services }
    - { role: grub, tags: grub }
